pkg/build: improve source finding message
Previously, users were not told where `kind` was looking for the
Kubernetes source, making the error message not actionable:

```
$ kind build node-image
ERROR: error building node image: error finding kuberoot: could not find kubernetes source
```

Now, we expose that information so the user can ensure we locate it.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>